# One-way array interpolate

In [1]:
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

In [296]:
x = np.array([0, 3, 5, 9, 10])

# 2D
y = np.array([[0, 300, 500, 900, 100], [0, 300, 500, 800, 100]])

# 1D
#y = np.array([0, 300, 500, 800, 100])

# Large
#y = np.tile(y, [2000,1])

In [282]:
# Ari Hartikainen's argmax trick
# Adapted to do left or right with the change in operator

import operator

def interpfill(x, y, kind='right', axis=-1):
    x = np.asanyarray(x)
    y = np.asanyarray(y)
    def func(xnew):
        kinds = {
            'left': operator.le,
            'right': operator.lt
        }
        xnew = np.asanyarray(xnew).reshape(-1, 1)
        idx = kinds[kind](xnew, x).argmax(1) - 1
        return np.take(y, idx, axis=axis)
    return func

In [303]:
f = interpfill(x, y)

xnew = np.arange(1, 12, 0.01)
f(xnew)

array([[  0,   0,   0, ..., 100, 100, 100],
       [  0,   0,   0, ..., 100, 100, 100],
       [  0,   0,   0, ..., 100, 100, 100],
       ..., 
       [  0,   0,   0, ..., 100, 100, 100],
       [  0,   0,   0, ..., 100, 100, 100],
       [  0,   0,   0, ..., 100, 100, 100]])

In [284]:
# Dieter Werthmüller's `searchsorted` trick

def interpfill(x, y, kind='right', axis=-1):
    x = np.asanyarray(x)
    y = np.asanyarray(y)
    def func(xnew):
        xnew = np.asanyarray(xnew).reshape(-1, 1)
        idx = np.searchsorted(x, xnew, side=kind) - 1
        values = np.take(y, idx, axis=axis)
        return values.reshape(y.shape[0], -1)
    return func

In [304]:
f = interpfill(x, y)

xnew = np.arange(1, 12, 0.01)
f(xnew)

array([[  0,   0,   0, ..., 100, 100, 100],
       [  0,   0,   0, ..., 100, 100, 100],
       [  0,   0,   0, ..., 100, 100, 100],
       ..., 
       [  0,   0,   0, ..., 100, 100, 100],
       [  0,   0,   0, ..., 100, 100, 100],
       [  0,   0,   0, ..., 100, 100, 100]])

## Compare with `scipy.interpolate`

In [286]:
from scipy.interpolate import interp1d

g = interp1d(x, y, kind='nearest', bounds_error=False, fill_value='extrapolate')
g(xnew)

array([[   0.,    0.,    0., ...,  100.,  100.,  100.],
       [   0.,    0.,    0., ...,  100.,  100.,  100.]])